[project]
name = "freeports-formats"
description = "Format definitions for the freeports PDF extraction framework"
requires-python = ">=3.8"
license = "GPL-3.0"
version = "0.0.1"
authors = [
    {name = "Oreste Sciacqualegni", email = "orestesciacqualegni@tutanota.com"},
]
dependencies = [
    "freeports",
]

[project.urls]
github = "https://github.com/tvp-freeports/analysis_finance_reports_formats"
documentation = "https://docs.freeports.org"
homepage = "https://www.freeports.org"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []
